/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:44:23 CET 2013
* 
* Call the script: _dummy = this execvm "explosives.sqf";
* 
*/

 _crate = _this select 0;
 clearweaponcargo _crate;
 clearmagazinecargo _crate;

