/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Wed Jan 23 23:36:51 CET 2013
* 
* Call the script: _dummy = this execvm "crate.sqf";
* 
*/

 _crate = _this select 0;
clearweaponcargo _crate;
clearmagazinecargo _crate;

_crate addweaponcargo ["M16A2",8];
_crate addmagazinecargo ["20Rnd_556x45_Stanag",20];

