/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:28:59 CET 2013
* 
* Call the script: _dummy = this execvm "m240.sqf";
* 
*/


 clearweaponcargo _crate;
 clearmagazinecargo _crate;

 _crate addweaponcargo ["ACE_BAF_L7A2_GPMG",8];
 _crate addweaponcargo ["ACE_M240B",8];
 _crate addweaponcargo ["M240",8];
 _crate addweaponcargo ["m240_scoped_EP1",8];
 _crate addweaponcargo ["ACE_M240L",8];
 _crate addweaponcargo ["ACE_M240L_M145",8];
 _crate addweaponcargo ["ACE_M60",8];
 _crate addweaponcargo ["M60A4_EP1",8];
 _crate addweaponcargo ["Mk_48_DES_EP1",8];
 _crate addweaponcargo ["Mk_48",8];
 _crate addmagazinecargo ["100Rnd_762x51_M240",16];
