/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:30:36 CET 2013
* 
* Call the script: _dummy = this execvm "m249.sqf";
* 
*/

 _crate = _this select 0;
 clearweaponcargo _crate;
 clearmagazinecargo _crate;

 _crate addweaponcargo ["ACE_M249_AIM",16];
 _crate addweaponcargo ["M249_m145_EP1",16];
 _crate addweaponcargo ["ACE_M249_PIP_ACOG",16];
 _crate addweaponcargo ["M249_EP1",16];
 _crate addweaponcargo ["M249",16];
 _crate addweaponcargo ["M249_TWS_EP1",16];
 _crate addweaponcargo ["m8_SAW",16];
 _crate addmagazinecargo ["100Rnd_556x45_BetaCMag",16];
 _crate addmagazinecargo ["100Rnd_556x45_M249",16];
 _crate addmagazinecargo ["200Rnd_556x45_L110A1",16];
 _crate addmagazinecargo ["200Rnd_556x45_M249",16];
 _crate addmagazinecargo ["20Rnd_556x45_Stanag",16];
 _crate addmagazinecargo ["30Rnd_556x45_Stanag",16];
 _crate addmagazinecargo ["30Rnd_556x45_StanagSD",16];
 _crate addmagazinecargo ["ACE_100Rnd_556x45_T_M249",16];
 _crate addmagazinecargo ["ACE_200Rnd_556x45_T_M249",16];
 _crate addmagazinecargo ["ACE_30Rnd_556x45_SB_S_Stanag",16];
 _crate addmagazinecargo ["ACE_30Rnd_556x45_SB_Stanag",16];
 _crate addmagazinecargo ["ACE_30Rnd_556x45_T_Stanag",16];
