/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:50:23 CET 2013
* 
* Call the script: _dummy = this execvm "optical.sqf";
* 
*/

 _crate = _this select 0;
 clearweaponcargo _crate;
 clearmagazinecargo _crate;

 _crate addweaponcargo ["Binocular",10];
 _crate addweaponcargo ["Laserdesignator",10];
 _crate addweaponcargo ["ACE_MX2A",10];
 _crate addweaponcargo ["NVGoggles",10];
 _crate addweaponcargo ["ACE_Rangefinder_OD",10];
 _crate addweaponcargo ["ACE_YardAge450",10];
 _crate addweaponcargo ["Binocular_Vector",10];
 _crate addweaponcargo ["ACE_Javelin_CLU",10];
 _crate addmagazinecargo ["ACE_Battery_Rangefinder",10];
 _crate addmagazinecargo ["Laserbatteries",10];
