/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:31:41 CET 2013
* 
* Call the script: _dummy = this execvm "pistols.sqf";
* 
*/

 _crate = _this select 0;
 clearweaponcargo _crate;
 clearmagazinecargo _crate;

