/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:45:33 CET 2013
* 
* Call the script: _dummy = this execvm "crew.sqf";
* 
*/


 clearweaponcargo _this;
 clearmagazinecargo _this;

