/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:13:27 CET 2013
* 
* Call the script: _dummy = this execvm "handgun.sqf";
* 
*/


 clearweaponcargo _this;
 clearmagazinecargo _this;

 _this addweaponcargo ["glock17_EP1",8];
 _this addweaponcargo ["ACE_Glock18",8];
 _this addweaponcargo ["Colt1911",8];
 _this addweaponcargo ["M9",8];
 _this addweaponcargo ["M9SD",8];
 _this addweaponcargo ["UZI_EP1",8];
 _this addweaponcargo ["UZI_SD_EP1",8];
 _this addweaponcargo ["ACE_P8",8];
 _this addweaponcargo ["revolver_EP1",8];
 _this addweaponcargo ["ACE_P226",8];
 _this addweaponcargo ["ACE_USPSD",8];
 _this addweaponcargo ["ACE_USP",8];
 _this addmagazinecargo ["17Rnd_9x19_glock17",16];
 _this addmagazinecargo ["ACE_33Rnd_9x19_G18",16];
 _this addmagazinecargo ["7Rnd_45ACP_1911",16];
 _this addmagazinecargo ["15Rnd_9x19_M9",16];
 _this addmagazinecargo ["15Rnd_9x19_M9SD",16];
 _this addmagazinecargo ["ACE_15Rnd_9x19_S_M9",16];
 _this addmagazinecargo ["30Rnd_9x19_UZI",16];
 _this addmagazinecargo ["30Rnd_9x19_UZI_SD",16];
 _this addmagazinecargo ["ACE_30Rnd_9x19_S_UZI",16];
 _this addmagazinecargo ["ACE_15Rnd_9x19_P8",16];
 _this addmagazinecargo ["6Rnd_45ACP",16];
 _this addmagazinecargo ["ACE_15Rnd_9x19_P226",16];
 _this addmagazinecargo ["ACE_12Rnd_45ACP_USP",16];
 _this addmagazinecargo ["ACE_12Rnd_45ACP_USPSD",16];
