/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:54:25 CET 2013
* 
* Call the script: _dummy = this execvm "item.sqf";
* 
*/


 clearweaponcargo _this;
 clearmagazinecargo _this;

 _this addweaponcargo ["ace_arty_rangeTable_2b14_legacy",2];
 _this addweaponcargo ["ACRE_PRC148",1];
 _this addweaponcargo ["ACRE_PRC148_UHF",1];
 _this addweaponcargo ["ACRE_PRC343",1];
 _this addweaponcargo ["ACE_GlassesSunglasses",2];
 _this addweaponcargo ["ACE_GlassesBalaklava",1];
 _this addweaponcargo ["ACE_GlassesBalaklavaGray",1];
 _this addweaponcargo ["ACE_GlassesBalaklavaOlive",1];
 _this addweaponcargo ["CDF_dogtags",2];
 _this addweaponcargo ["Cobalt_File",1];
 _this addweaponcargo ["ace_arty_rangeTable_d30_legacy",1];
 _this addweaponcargo ["ACE_DAGR",1];
 _this addweaponcargo ["ACE_KeyCuffs",1];
 _this addweaponcargo ["ACE_Earplugs",2];
 _this addweaponcargo ["EvMoscow",1];
 _this addweaponcargo ["EvKobalt",2];
 _this addweaponcargo ["EvMap",1];
 _this addweaponcargo ["PMC_documents",1];
 _this addweaponcargo ["EvMoney",1];
 _this addweaponcargo ["ACE_GlassesGasMask_RU",1];
 _this addweaponcargo ["ACE_HuntIR_monitor",2];
 _this addweaponcargo ["ACE_Kestrel4500",1];
 _this addweaponcargo ["Kostey_map_case",1];
 _this addweaponcargo ["Kostey_notebook",1];
 _this addweaponcargo ["Kostey_photos",1];
 _this addweaponcargo ["ace_arty_rangeTable_m119",1];
 _this addweaponcargo ["ace_arty_rangeTable_m119_legacy",1];
 _this addweaponcargo ["ace_arty_rangeTable_m224_legacy",1];
 _this addweaponcargo ["ace_arty_rangeTable_m252_legacy",1];
 _this addweaponcargo ["Moscow_Bombing_File",2];
 _this addweaponcargo ["ItemRadio",1];
 _this addweaponcargo ["ACE_GlassesLHD_glasses",2];
 _this addweaponcargo ["ACE_GlassesBlackSun",1];
 _this addweaponcargo ["ACE_GlassesGreenSun",2];
 _this addweaponcargo ["ACE_SpareBarrel",1];
 _this addweaponcargo ["ACE_SOFLAMTripod",1];
 _this addweaponcargo ["ACE_GlassesTactical",1];
