/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:54:25 CET 2013
* 
* Call the script: _dummy = this execvm "item.sqf";
* 
*/


 clearweaponcargo _this;
 clearmagazinecargo _this;

 _this addweaponcargo ["ace_arty_rangeTable_2b14_legacy",10];
 _this addweaponcargo ["ACRE_PRC148",10];
 _this addweaponcargo ["ACRE_PRC148_UHF",10];
 _this addweaponcargo ["ACRE_PRC343",10];
 _this addweaponcargo ["ACE_GlassesSunglasses",10];
 _this addweaponcargo ["ACE_GlassesBalaklava",10];
 _this addweaponcargo ["ACE_GlassesBalaklavaGray",10];
 _this addweaponcargo ["ACE_GlassesBalaklavaOlive",10];
 _this addweaponcargo ["CDF_dogtags",10];
 _this addweaponcargo ["Cobalt_File",10];
 _this addweaponcargo ["ace_arty_rangeTable_d30_legacy",10];
 _this addweaponcargo ["ACE_DAGR",10];
 _this addweaponcargo ["ACE_KeyCuffs",10];
 _this addweaponcargo ["ACE_Earplugs",10];
 _this addweaponcargo ["EvMoscow",10];
 _this addweaponcargo ["EvKobalt",10];
 _this addweaponcargo ["EvMap",10];
 _this addweaponcargo ["PMC_documents",10];
 _this addweaponcargo ["EvMoney",10];
 _this addweaponcargo ["ACE_GlassesGasMask_RU",10];
 _this addweaponcargo ["ACE_HuntIR_monitor",10];
 _this addweaponcargo ["ACE_Kestrel4500",10];
 _this addweaponcargo ["Kostey_map_case",10];
 _this addweaponcargo ["Kostey_notebook",10];
 _this addweaponcargo ["Kostey_photos",10];
 _this addweaponcargo ["ace_arty_rangeTable_m119",10];
 _this addweaponcargo ["ace_arty_rangeTable_m119_legacy",10];
 _this addweaponcargo ["ace_arty_rangeTable_m224_legacy",10];
 _this addweaponcargo ["ace_arty_rangeTable_m252_legacy",10];
 _this addweaponcargo ["Moscow_Bombing_File",10];
 _this addweaponcargo ["ItemRadio",10];
 _this addweaponcargo ["ACE_GlassesLHD_glasses",10];
 _this addweaponcargo ["ACE_GlassesBlackSun",10];
 _this addweaponcargo ["ACE_GlassesGreenSun",10];
 _this addweaponcargo ["ACE_SpareBarrel",10];
 _this addweaponcargo ["ACE_SOFLAMTripod",10];
 _this addweaponcargo ["ACE_GlassesTactical",10];
