/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:47:51 CET 2013
* 
* Call the script: _dummy = this execvm "launchers.sqf";
* 
*/


 clearweaponcargo _this;
 clearmagazinecargo _this;

 _this addweaponcargo ["ACE_Arty_M1A1_Collimator",4];
 _this addweaponcargo ["Javelin",4];
 _this addweaponcargo ["Stinger",4];
 _this addweaponcargo ["ACE_JerryCan_Dummy_15",4];
 _this addweaponcargo ["ACE_M122TripodProxy",4];
 _this addweaponcargo ["M136",4];
 _this addweaponcargo ["ACE_M136_CSRS",4];
 _this addweaponcargo ["ACE_Arty_AimingPost_M1A2_M58",4];
 _this addweaponcargo ["ACE_Arty_AimingPost_M1A2_M59",4];
 _this addweaponcargo ["ACE_M252Proxy",4];
 _this addweaponcargo ["ACE_M3TripodProxy",4];
 _this addweaponcargo ["ACE_M224TripodProxy",4];
 _this addweaponcargo ["ACE_M72A2",4];
 _this addweaponcargo ["ACE_M72",4];
 _this addweaponcargo ["SMAW",4];
 _this addweaponcargo ["ACE_MK19MOD3Proxy",4];
 _this addweaponcargo ["ACE_M220TripodProxy",4];
 _this addweaponcargo ["MAAWS",4];
 _this addmagazinecargo ["Javelin",10];
 _this addmagazinecargo ["Stinger",10];
 _this addmagazinecargo ["ACE_MAAWS_HE",10];
 _this addmagazinecargo ["MAAWS_HEAT",10];
 _this addmagazinecargo ["MAAWS_HEDP",10];
