/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Wed Jan 23 23:36:51 CET 2013
* 
* Call the script: _dummy = this execvm "crate.sqf";
* 
*/


while {true} do {
 if isnull _this exitwith {};
 if not alive _this exitwith {};
 clearweaponcargo _this;
 clearmagazinecargo _this;

 _this addweaponcargo ["M16A2",4];
 _this addmagazinecargo ["20Rnd_556x45_Stanag",20];

 sleep 60*5;
};
