/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:28:59 CET 2013
* 
* Call the script: _dummy = this execvm "m240.sqf";
* 
*/


 clearweaponcargo _this;
 clearmagazinecargo _this;

 _this addweaponcargo ["ACE_BAF_L7A2_GPMG",4];
 _this addweaponcargo ["ACE_M240B",1];
 _this addweaponcargo ["M240",1];
 _this addweaponcargo ["m240_scoped_EP1",1];
 _this addweaponcargo ["ACE_M240L",1];
 _this addweaponcargo ["ACE_M240L_M145",1];
 _this addweaponcargo ["ACE_M60",1];
 _this addweaponcargo ["M60A4_EP1",1];
 _this addweaponcargo ["Mk_48_DES_EP1",1];
 _this addweaponcargo ["Mk_48",1];
 _this addmagazinecargo ["100Rnd_762x51_M240",16];
