/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:50:23 CET 2013
* 
* Call the script: _dummy = this execvm "optical.sqf";
* 
*/


 clearweaponcargo _this;
 clearmagazinecargo _this;

 _this addweaponcargo ["Binocular",10];
 _this addweaponcargo ["Laserdesignator",10];
 _this addweaponcargo ["ACE_MX2A",10];
 _this addweaponcargo ["NVGoggles",10];
 _this addweaponcargo ["ACE_Rangefinder_OD",10];
 _this addweaponcargo ["ACE_YardAge450",10];
 _this addweaponcargo ["Binocular_Vector",10];
 _this addweaponcargo ["ACE_Javelin_CLU",10];
 _this addmagazinecargo ["ACE_Battery_Rangefinder",10];
 _this addmagazinecargo ["Laserbatteries",10];
