/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:50:23 CET 2013
* 
* Call the script: _dummy = this execvm "optical.sqf";
* 
*/


 clearweaponcargo _this;
 clearmagazinecargo _this;

 _this addweaponcargo ["Binocular",2];
 _this addweaponcargo ["Laserdesignator",3];
 _this addweaponcargo ["ACE_MX2A",2];
 _this addweaponcargo ["NVGoggles",1];
 _this addweaponcargo ["ACE_Rangefinder_OD",1];
 _this addweaponcargo ["ACE_YardAge450",1];
 _this addweaponcargo ["Binocular_Vector",1];
 _this addweaponcargo ["ACE_Javelin_CLU",2];
 _this addmagazinecargo ["ACE_Battery_Rangefinder",1];
 _this addmagazinecargo ["Laserbatteries",1];
