/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:56:39 CET 2013
* 
* Call the script: _dummy = this execvm "rucks.sqf";
* 
*/


 clearweaponcargo _this;
 clearmagazinecargo _this;

 _this addweaponcargo ["ACRE_PRC117F",10];
 _this addweaponcargo ["ACE_CharliePack_WMARPAT",10];
 _this addweaponcargo ["ACE_CharliePack_Multicam",10];
 _this addweaponcargo ["ACE_Backpack_US",10];
 _this addweaponcargo ["ACE_Coyote_Pack",10];
 _this addweaponcargo ["ACE_Coyote_Pack_Flora",10];
 _this addweaponcargo ["ACE_Coyote_Pack_Multicam",10];
 _this addweaponcargo ["ACE_FAST_PackEDC",10];
 _this addweaponcargo ["ACE_FAST_PackEDC_ACU",10];
 _this addweaponcargo ["ACE_Rucksack_MOLLE_Wood",10];
 _this addweaponcargo ["ACE_Rucksack_MOLLE_Green_Medic",10];
 _this addweaponcargo ["ACE_Rucksack_MOLLE_ACU_Medic",10];
 _this addweaponcargo ["ACE_PRC119_MAR",10];
 _this addweaponcargo ["ACE_VTAC_RUSH72_OD",10];
 _this addweaponcargo ["ACE_VTAC_RUSH72",10];
