/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.70
* Thu Jan 24 00:42:40 CET 2013
* 
* Call the script: _dummy = this execvm "sniper.sqf";
* 
*/


 clearweaponcargo _this;
 clearmagazinecargo _this;

 _this addweaponcargo ["ACE_AS50",4];
 _this addweaponcargo ["m107",4];
 _this addweaponcargo ["m107_TWS_EP1",4];
 _this addweaponcargo ["ACE_M109",4];
 _this addweaponcargo ["M110_NVG_EP1",4];
 _this addweaponcargo ["ACE_M110_SD",4];
 _this addweaponcargo ["M110_TWS_EP1",4];
 _this addweaponcargo ["DMR",4];
 _this addweaponcargo ["M24",4];
 _this addweaponcargo ["M24_des_EP1",4];
 _this addweaponcargo ["M40A3",4];
 _this addweaponcargo ["ACE_TAC50",4];
 _this addweaponcargo ["ACE_TAC50_SD",4];
 _this addmagazinecargo ["5Rnd_127x99_as50",10];
 _this addmagazinecargo ["ACE_5Rnd_127x99_B_TAC50",10];
 _this addmagazinecargo ["ACE_5Rnd_127x99_S_TAC50",10];
 _this addmagazinecargo ["ACE_5Rnd_127x99_T_TAC50",10];
 _this addmagazinecargo ["10Rnd_127x99_m107",10];
 _this addmagazinecargo ["ACE_10Rnd_127x99_T_m107",10];
 _this addmagazinecargo ["ACE_10Rnd_127x99_Raufoss_m107",10];
 _this addmagazinecargo ["ACE_5Rnd_25x59_HEDP_Barrett",10];
 _this addmagazinecargo ["20Rnd_762x51_B_SCAR",10];
 _this addmagazinecargo ["20Rnd_762x51_SB_SCAR",10];
 _this addmagazinecargo ["ACE_20Rnd_762x51_SB_M110",10];
 _this addmagazinecargo ["ACE_20Rnd_762x51_T_M110",10];
 _this addmagazinecargo ["ACE_20Rnd_762x51_T_SCAR",10];
 _this addmagazinecargo ["ACE_20Rnd_762x51_S_M110",10];
 _this addmagazinecargo ["ACE_20Rnd_762x51_S_SCAR",10];
 _this addmagazinecargo ["ACE_20Rnd_762x51_SB_S_SCAR",10];
 _this addmagazinecargo ["20Rnd_762x51_DMR",10];
 _this addmagazinecargo ["ACE_20Rnd_762x51_B_M14",10];
 _this addmagazinecargo ["ACE_20Rnd_762x51_S_DMR",10];
 _this addmagazinecargo ["ACE_20Rnd_762x51_S_M14",10];
 _this addmagazinecargo ["ACE_20Rnd_762x51_T_DMR",10];
 _this addmagazinecargo ["5Rnd_762x51_M24",10];
 _this addmagazinecargo ["ACE_5Rnd_762x51_T_M24",10];
